export default class CompanyProfile {
    constructor(public address?: string,
                public city?: string,
                public country?: string,
                public currency?: string,
                public cusip?: string,
                public description?: string,
                public exchange?: string,
                public ggroup?: string,
                public gind?: string,
                public gsector?: string,
                public gsubind?: string,
                public ipo?: string,
                public isin?: string,
                public naics?: string,
                public name?: string,
                public phone?: string,
                public state?: string,
                public ticker?: string,
                public weburl?: string) {}
}